* Bind a key to two different commands
  <2017-01-09 Mon>

  When =electric-pair-mode= is enabled, the key =DEL= is interesting:
  when the point is at the end of a empty quote such as "", it runs
  =electric-pair-delete-pair=, otherwise it runs original command such
  as =org-delete-backward-char= in Org mode.

  For example, =RET= calls =emacs-version= when point is at the
  beginning of the line, otherwise it works normally.

  #+BEGIN_SRC emacs-lisp
  (defvar foo-mode-map
    (let ((map (make-sparse-keymap)))
      (define-key map (kbd "RET")
        `(menu-item
          "" emacs-version
          :filter
          ,(lambda (cmd)
             (and (bolp)
                  cmd))))
      map))

  (define-minor-mode foo-mode
    "Foo."
    :lighter " Foo"
    :global t)
  #+END_SRC

  This can be useful since the key can still run *original* command without knowing what it is.

  For documentation, see [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Extended-Menu-Items.html][(elisp) Extended Menu Items]].

* 输入中文标点符号

  根据 [[https://github.com/ruanyf/document-style-guide/blob/master/docs/marks.md][ruanyf/document-style-guide#标点符号]] 整理的常用中文标点：

  | 名称         | 符号 | Code （用 C-x 8 输入） |
  |--------------+------+---------------|
  | 句号         | 。   | #x3002        |
  | 逗号         | ，   | #xFF0C        |
  | 顿号         | 、   | #x3001        |
  | 分号         | ；   | #xFF1B        |
  | 双引号       | “”   | #x201C #x201D |
  | 单引号       | ‘’   | #x2018 #x2019 |
  | 圆括号       | （） | #xFF08 #xFF09 |
  | 冒号         | ：   | #xFF1A        |
  | 省略号       | ……   | #x2026 #x2026 |
  | 感叹号       | ！   | #xFF01        |
  | 破折号       | ——   | #x2014 #x2014 |
  | 短横线连接号 | -    | #x2D          |
  | 一字连接号   | —    | #x2014        |
  | 波浪连接号   | ～   | #xFF5E        |
  | 书名号       | 《》 | #x300A #x300B |

  关于详细的标点符号的使用应当参考 [[http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf][中华人民共和国国家标准 GB/T 15834-2011]]，维基百科上对比了不同标准下的标点符号——[[https://zh.wikipedia.org/wiki/%25E6%25A0%2587%25E7%2582%25B9%25E7%25AC%25A6%25E5%258F%25B7][标点符号 - 维基百科，自由的百科全书]]。

** TODO 输入直角引号（台湾） [0/2]
   - [ ] 输入
   - [ ] 弯引号 <=> 直角引号（ =cycle-chinese-quotes= ）

* Use the syntax of GNU ChangeLog entries for commit message
  <2017-01-11 Wed>

  To build [[https://www.gnu.org/prep/standards/html_node/Change-Logs.html][(info "(standards) Change Logs")]]:
  1. (Default) Put point to the file I have changed, and type ~C-x 4 a~ or ~M-x add-change-log-entry~, then cut-and-paste or ~C-x v v~
  2. (Magit) Put point on the diff, and type ~C~ (~magit-commit-add-log~)

* Emacs Lisp Packaging

  | Type            | Author's Task                                                      | ELPA's Task                                         |
  |-----------------+--------------------------------------------------------------------+-----------------------------------------------------|
  | Single .el file | Nothing                                                            | Provide package metadata (archive) and the .el file |
  | Multiple files  | Write foo-pkg.el (don't write foo-autoloads.el) then tar the files | Provide package metadata (archive) and the tar file |

  Melpa & Melpa-Stable build the tar file for multiple files
  automatically, and there is no need to provide =foo-pkg.el= since it
  will be created automatically as well.

  One can use =M-x package-install-file= to install a tar file.
