#+TITLE: Emacs Solutions to [[http://www.vimgolf.com/][VimGolf]]
#+OPTIONS: toc:nil

#+NAME: progress
| Total | Done |   (%) |
|-------+------+-------|
|   345 |  165 | 47.83 |
#+TBLFM: $2='(count-matches "^* ")::$3=($2/$1)*100;p4

#+TOC: headlines 1

* [[https://vimgolf.com/challenges/510b1c61e48b7e0002000028][Chinese Multiplication Table]]
<2017-01-29 Sun>

#+BEGIN_SRC emacs-lisp :exports both
(loop for i from 1 to 9
      concat (concat
              (mapconcat #'identity
                         (loop for j from 1 to i
                               collect (format "%d*%d=%d" i j (* i j)))
                         " ")
              "\n"))
#+END_SRC

#+RESULTS:
: 1*1=1
: 2*1=2 2*2=4
: 3*1=3 3*2=6 3*3=9
: 4*1=4 4*2=8 4*3=12 4*4=16
: 5*1=5 5*2=10 5*3=15 5*4=20 5*5=25
: 6*1=6 6*2=12 6*3=18 6*4=24 6*5=30 6*6=36
: 7*1=7 7*2=14 7*3=21 7*4=28 7*5=35 7*6=42 7*7=49
: 8*1=8 8*2=16 8*3=24 8*4=32 8*5=40 8*6=48 8*7=56 8*8=64
: 9*1=9 9*2=18 9*3=27 9*4=36 9*5=45 9*6=54 9*7=63 9*8=72 9*9=81

注意上面有两处没有对齐。

* [[https://vimgolf.com/challenges/56fb2e75ccffcc0009026473][One number per line]]
<2017-01-29 Sun>

1. ~M-x replace-string RET , RET C-q C-j RET~
2. ~M-x delete-matching-lines RET ^$ RET~

* [[https://vimgolf.com/challenges/52c3cb0d9b8634000200000e][A HAPPY NEW YEAR 2014 !]]
<2017-01-29 Sun>

If necessary, use ~M-x org-increase-number-at-point~ or similar to
increase/decrease number at point.

* [[https://vimgolf.com/challenges/54862fbb3f90ac0002904cf5][Just the middle]]
<2017-01-29 Sun>

Just edit like in any normal text editor. Or mark the region of text
which is useful and run the following command.

#+BEGIN_SRC emacs-lisp
(defun delete-whole-buffer-but-region (beg end)
  (interactive "*r")
  (delete-region end (point-max))
  (delete-region (point-min) beg))
#+END_SRC

* [[https://vimgolf.com/challenges/5462e3f41198b80002512673][I forgot quotes]]
<2017-01-29 Sun>

1. Enable ~electric-pair-mode~
2. Mark the region of text which needs quotes and enter one ~"~

* [[http://www.vimgolf.com/challenges/55bcdc3ef4219f456102374f][Vice versa]]
<2017-01-29 Sun>

> Little role switching.

#+BEGIN_SRC diff
- The quick brown fox jumps over the lazy dog.
+ The quick lazy dog jumps over the brown fox.
#+END_SRC

** Solution

Hmm, I have made a package (swap-regions) for this.

1. Select "brown fox" and cancel it with ~C-g~
2. Select "lazy dog"
3. ~M-x swap-regions~

* [[http://www.vimgolf.com/challenges/5192f96ad8df110002000002][Words in parens]]
<2017-01-29 Sun>

Start file:

#+BEGIN_EXAMPLE
one two
three
#+END_EXAMPLE

End file:

#+BEGIN_EXAMPLE
(one) (two)
(three)
#+END_EXAMPLE

** Solution

*** Solution 1 with ~electric-pair-mode~

Enable it if necessary

1. Mark the word
2. Hit ~(~

*** Solution 2 with ~paredit-mode~

Enable it if necessary

1. Move point to the word and hit ~M-(~

By the way, 1) mark the word 2) hit ~(~. works too.

* [[http://www.vimgolf.com/challenges/56d70389bbbe462aff01d42a][Swap values]]
<2017-01-29 Sun>

#+BEGIN_SRC diff
- name=www-data, groups=developer
+ name=developer, groups=www-data
#+END_SRC

Use ~swap-regions~.

* [[http://www.vimgolf.com/challenges/53d93fc3768e280002124f23][V to the i]]
<2017-01-29 Sun>

#+BEGIN_QUOTE
Input is 99 V's. Output is 100 i's.
#+END_QUOTE

#+BEGIN_SRC diff
- VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
+ iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
#+END_SRC

** Solution

1. ~C-k~
2. ~C-u 100 i~ (or simply type ~M-1 0 0 i~)

* [[http://www.vimgolf.com/challenges/540629666a1e4000020d9e5a][-a-b-c-]]
<2017-01-29 Sun>

#+BEGIN_SRC diff
- abcdefghijklm
+ -a-b-c-d-e-f-g-h-i-j-k-l-m-
#+END_SRC

** Solution

#+BEGIN_SRC emacs-lisp
(defun put-hyphens-everywhere (beg end)
  (interactive "*r")
  (insert
   (concat "-"
           (mapconcat #'string
                      (string-to-list (delete-and-extract-region beg end))
                      "-")
           "-")))
#+END_SRC

* [[http://www.vimgolf.com/challenges/4f0720c8f037090001000007][switch variable]]
<2017-01-29 Sun>

#+BEGIN_SRC diff
- int barins, foovariable = 1;
+ int foovariable, barins = 1;
#+END_SRC

** Solution

~M-t~ (~transpose-words~) should just work for this case, thougth it
is better to use ~C-M-t~ (~transpose-sexps~).

* [[https://vimgolf.com/challenges/57343555fd77ad227900df4a][Split line with dots]]
<2017-01-29 Sun>

Start file

#+BEGIN_SRC ruby
class VimGolf
  def split_me
    MyModel .first_method.second_method(arg).third_method(arg.method_one.method_two)
  end
end
#+END_SRC

End file

#+BEGIN_SRC ruby
class VimGolf
  def split_me
    MyModel
      .first_method
      .second_method(arg)
      .third_method(arg.method_one.method_two)
  end
end
#+END_SRC

** Solution

~electric-indent-mode~ defaults to ~t~, thus simply ~RET~ will indent
code automatically. So the solution is moving point to ~.~ and type
~RET~.

Just in case, I would have to repeat it a lot: define the following
keyboard macro with ~<f3>~ and ~<f4>~ or ~C-x (~ and ~C-x )~.

#+BEGIN_EXAMPLE
C-s . C-b RET C-f
#+END_EXAMPLE

Run the last keyboard macro with ~C-x e~
(~kmacro-end-and-call-macro~).

* [[https://vimgolf.com/challenges/583112d0215b7c3ed2016bdb][Order and join]]
<2017-01-29 Sun>

Start file

#+BEGIN_EXAMPLE
four
one
two
five
three
six
#+END_EXAMPLE

End file

#+BEGIN_EXAMPLE
one two three
four five
six
#+END_EXAMPLE

** Solution

Type ~M-^~ (~delete-indentation~ or its alias ~join-line~) for several
times and in several places.

* [[https://vimgolf.com/challenges/559c30948ef59c0eb7000002][Collect List]]
<2017-01-29 Sun>

Start file

#+BEGIN_EXAMPLE
  * item1
  * item2
  * item3
  * item4
  * item5
#+END_EXAMPLE

End file

#+BEGIN_EXAMPLE
item1,item2,item3,item4,item5
#+END_EXAMPLE

** Solution

1. Remove the prefix "* "
   1. Mark the rectangle region with ~C-x SPC~
   2. Delete it with ~C-w~
2. Join the line with "," by ~M-% C-q C-j RET , RET~ (~query-replace~)

* [[https://vimgolf.com/challenges/576c778ea4896a561b01b4f2][Copy three lines]]
<2017-01-29 Sun>

1. Mark the text and copy it with ~M-w~
2. Yank the text with ~M-y~ (~helm-show-kill-ring~) and delete unneeded
   text with ~C-k~
3. Repeat step 2

* [[https://vimgolf.com/challenges/54595b13128576000257a3c1][Basic renumbering]]
<2017-01-29 Sun>

Start file

#+BEGIN_EXAMPLE
10 PRINT "The actual"
15 PRINT "code doesn't"
16 PRINT "really matter."
20 PRINT "Just take"
25 PRINT "care of"
30 PRINT "the numbers."
#+END_EXAMPLE

End file

#+BEGIN_EXAMPLE
10 PRINT "The actual"
20 PRINT "code doesn't"
30 PRINT "really matter."
40 PRINT "Just take"
50 PRINT "care of"
60 PRINT "the numbers."
#+END_EXAMPLE

** Solution

- Remove old prefix with ~C-x SPC~ (~rectangle-mark-mode~) and ~C-w~
- Insert new prefix with the following command (Notes that ~C-x r N~
  (~rectangle-number-lines~)'s step always is 1 thus doesn't work
  here)

#+BEGIN_SRC emacs-lisp
(defun number-region (start end start-at step)
  (interactive "*r\nnNumber to count from: \nnStep: ")
  (apply-on-rectangle (lambda (start end _arg)
                        (move-to-column start t)
                        (insert (format "%d " start-at))
                        (incf start-at step))
                      start end nil))
#+END_SRC

* [[https://vimgolf.com/challenges/51f4a64c6813e30002000018][quotes inside quotes]]
<2017-01-30 Mon>

Start file

#+BEGIN_EXAMPLE
This string contains a 'quoted' word.
This string contains 'two' quoted 'words.'
This 'string doesn't make things easy.'
#+END_EXAMPLE

End file

#+BEGIN_EXAMPLE
This string contains a "quoted" word.
This string contains "two" quoted "words."
This "string doesn't make things easy."
#+END_EXAMPLE

** Solution

1. Mark the text (including quotes)
2. Call the following command

#+BEGIN_SRC emacs-lisp
(defun toggle-single-and-double-quote (beg end)
  (interactive "*r")
  (let ((s (buffer-substring beg end))
        double-p)
    (if (and (> (length s) 2)
             (let ((left (aref s 0))
                   (right (aref s (1- (length s)))))
               (or (= left right ?')
                   (prog1 (= left right ?\")
                     (setq double-p t)))))
        (progn (delete-region beg end)
               (insert (if double-p ?' ?\")
                       (substring s 1 -1)
                       (if double-p ?' ?\")))
      (message "You need mark a region of \"'foo'\" before calling this"))))
#+END_SRC

The following can help editing pairs or quotes under some particular
situations nicely.

- ~electric-pair-mode~ (built-in)
- ParEdit (ELPA)
- cycle-quotes (ELPA)

* [[https://vimgolf.com/challenges/571808767dd9d30009000001][Align commas]]
<2017-01-30 Mon>

Start file

#+BEGIN_EXAMPLE
just = make,
       all,
       the,
       commas,
       line,
       up
#+END_EXAMPLE

End file

#+BEGIN_EXAMPLE
just = make  ,
       all   ,
       the   ,
       commas,
       line  ,
       up
#+END_EXAMPLE

** Solution

~M-x align-regexp RET , RET~ works out of box. Though, I still don't
know how this works. I will need to figure this out once facing more
complex task.

* [[https://vimgolf.com/challenges/4d1a1c36567bac34a9000002][Reformat/Refactor a Golfer Class]]
<2017-01-30 Mon>

Just edit normally.

* [[https://vimgolf.com/challenges/4d1a8bf2b8cb3409320002c4][Search and Replace 0]]
<2017-01-30 Mon>

~M-% aaa RET xaaax RET~

* [[https://vimgolf.com/challenges/53c66c482b4166000226bbee][Don't know what this is]]
<2017-01-30 Mon>

Start file

#+BEGIN_EXAMPLE
[1:0]
[0:1]
[1:100]
[0:100]
#+END_EXAMPLE

End file

#+BEGIN_EXAMPLE
[   ]
[   ]
[     ]
[     ]
#+END_EXAMPLE

** Solution

Use ~C-M-%~ (~query-replace-regexp~) then replace

- ~\[\(.\)\]~ with
- ~\,(format "[%s]" (make-string (length \1) ? ))~

For the use of ~\,~, see [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Regexp-Replace.html][(info "(emacs) Regexp Replace")]].

* [[http://www.vimgolf.com/challenges/56ef78d9f604b51ec4007b8d][Scrambled numbers]]
<2017-01-30 Mon>

Start file

#+BEGIN_EXAMPLE
Four is 1.
One is 2.
Five is 3.
Three is 4.
Six is 5.
Two is 6.
#+END_EXAMPLE

End file

#+BEGIN_EXAMPLE
One is 1.
Two is 2.
Three is 3.
Four is 4.
Five is 5.
Six is 6.
#+END_EXAMPLE

** Solution

- Enable ~swap-word-mode~ then
- swap word up/down with ~<M-down>~ and ~<M-up>~

#+BEGIN_SRC emacs-lisp
(defun swap-word-up->down ()
  (interactive)
  (let ((b1 (bounds-of-thing-at-point 'word))
        s1 e1 t1
        s2 e2 t2)
    (when b1
      (setq s1 (car b1)
            e1 (cdr b1)
            t1 (buffer-substring s1 e1))
      (save-excursion
        (forward-line 1)
        (setq b2 (bounds-of-thing-at-point 'word)
              s2 (car b2)
              e2 (cdr b2)
              t2 (buffer-substring s2 e2))
        (delete-region s2 e2)
        (insert t1))
      (delete-region s1 e1)
      (insert t2))))

(defun swap-word-down->up ()
  (interactive)
  (let ((b1 (bounds-of-thing-at-point 'word))
        s1 e1 t1
        b2 s2 e2 t2)
    (when b1
      (save-excursion
        (forward-line -1)
        (setq b2 (bounds-of-thing-at-point 'word))
        (when b2
          (setq s1 (car b1)
                e1 (cdr b1)
                t1 (buffer-substring s1 e1)
                s2 (car b2)
                e2 (cdr b2)
                t2 (buffer-substring s2 e2))))
      (delete-region s1 e1)
      (insert t2)
      (forward-line -1)
      (delete-region s2 e2)
      (insert t1))))

(define-minor-mode swap-word-mode
  "Swap word up/down."
  :init nil
  :lighter " Swap word"
  :keymap (let ((map (make-sparse-keymap)))
            (define-key map (kbd "<M-up>")  #'swap-word-down->up)
            (define-key map (kbd "<M-down>") #'swap-word-up->down)
            map))
#+END_SRC

* [[http://www.vimgolf.com/challenges/54df95a4a4b28331e9000003][Space out the alphabet]]
<2017-01-30 Mon>

1. ~M-x replace-regexp RET \(.\) RET    \1 RET~
2. Delete leading white spaces with rectangle mark mode.

By the way, I don't know how a regexp which matches any character but
not at the beginning of a line.

* [[http://www.vimgolf.com/challenges/4f438739f5a8d70001000019][replacing each line of a block selection]]
<2017-01-30 Mon>

Replace (or query-replace) string (or regexp) as usual.

* [[http://www.vimgolf.com/challenges/4ef209ef78702b0001000019][Make it more readable]]
<2017-01-30 Mon>

- Replace ~#~ with ~\n\n#~ with ~M-x replace-string~
- Delete leading empty lines with the most obvious way (that is,
  delete multiple times or mark then delete)

* [[http://www.vimgolf.com/challenges/539c50b188b4e20002053e38][Where should I put the Newline?]]
<2017-01-30 Mon>

Replace (or query-replace) ~--->newline<---~ with ~--->\n<---~. Notes,
to enter ~\n~ from MiniBuffer, type ~C-q C-j~ (~C-q~ is bound to
~quoted-insert~).

* [[http://www.vimgolf.com/challenges/4d716c76919202611400002b][Numbering a List]]
<2017-01-30 Mon>

1. Mark the region
2. ~C-u C-x r N RET %1d. RET~ (i.e., call ~rectangle-number-lines~
   with a prefix argument, and use the default start (that is 1), and
   enter the format)

* [[http://www.vimgolf.com/challenges/54345d14d529ef0002227d4c][That hyphen]]
<2017-01-30 Mon>

Just normal edit.

* [[http://www.vimgolf.com/challenges/58409414770f4b474601384c][Sort files from hosts]]
<2017-01-31 Tue>

Start file

#+BEGIN_EXAMPLE
dartacan: /etc/hosts
dartacan: /etc/httpd/conf/httpd.conf
dartacan: /opt/scripts/list_vhosts
mozart: /etc/resolv.conf
mozart: /usr/bin/vim
mozart: /usr/bin/awesome
mozart: ~/.gem/ruby/2.1.0/bin/vimgolf
gullit: /bin/bash
gullit: /etc/hosts
gullit: /usr/bin/xorg
gullit: /usr/bin/xeyes
gullit: /usr/bin/X
gullit: /
#+END_EXAMPLE

End file

#+BEGIN_EXAMPLE
dartacan: /etc/hosts /etc/httpd/conf/httpd.conf /opt/scripts/list_vhosts
mozart: /etc/resolv.conf /usr/bin/vim /usr/bin/awesome ~/.gem/ruby/2.1.0/bin/vimgolf
gullit: /bin/bash /etc/hosts /usr/bin/xorg /usr/bin/xeyes /usr/bin/X /
#+END_EXAMPLE

** Solution

1. Define the following keyboard macro with ~C-x (~ and ~C-x )~
2. Execute it with ~C-x e~ by moving point accordingly or ~M-x
   apply-macro-to-region-lines~ by select the region.

#+BEGIN_EXAMPLE
Last macro: C-a C-SPC C-s : C-f C-w M-^
#+END_EXAMPLE

* [[http://www.vimgolf.com/challenges/57a208ce38e7e83a43000003][Generate a list of numbers]]
<2017-01-31 Tue>

#+BEGIN_QUOTE
Please generate list of numbers from 1 to 20.
#+END_QUOTE

** Solution

#+BEGIN_SRC emacs-lisp
(loop for i from 1 to 20
      do (insert (format "%s " i)))
#+END_SRC

* [[http://www.vimgolf.com/challenges/536cfa23fcccd100025678bd][Extract argument from function]]
<2017-01-31 Tue>

Nothing special, edit as usual.

* [[http://www.vimgolf.com/challenges/4d1a4d82a860b7447200008d][Whitespace, empty lines and tabs]]
<2017-01-31 Tue>

1. Replace one tab with one space with query-replace or just replace
2. Strip trailing whitespace with ~M-x delete-trailing-whitespace~
3. Delete empty lines with ~M-x delete-matching-lines ^$~

In Emacs, ~untabify~ and ~whitespace-cleanup~ are much more sophisticated.

* [[http://www.vimgolf.com/challenges/5100ce70326e09000200004a][Saving the hashes(#)]]
<2017-01-31 Tue>

#+BEGIN_QUOTE
Our goal is to delete every line which doesn't contain a hash
signs. The remaining hash signs with numbers are then sorted to get
the final output.
#+END_QUOTE

** Solution

1. Delete line which don't contain a hash with ~M-x delete-non-matching-lines #~
2. Make all # on its own line with replace " #" with "\n#"
3. Reverse the lines (since it's sorted already) with ~M-x reverse-region~

* [[http://www.vimgolf.com/challenges/5421e49fdbded100021e4934][Count both ways]]
<2017-01-31 Tue>

1. Copy "two three four five six seven eight nine ten eleven" and
   paste it to next line
2. Mark the second line and replace " " with "\n" with ~M-x
   replace-string~.

* [[http://www.vimgolf.com/challenges/5526aef5814f89118e00f23c][camel riding]]
<2017-01-31 Tue>

#+BEGIN_SRC diff
-val (schemas, activeCount, techTagCount, sharedCount, allowedPathsCount, rootCount, searchableCount) = fieldStats(store)
+val (schemas, schActiveCount, schTechTagCount, schSharedCount, schAllowedPathsCount, schRootCount, schSearchableCount) = fieldStats(store)
#+END_SRC

Define a keyboard macro of simple edit plus ~M-x upcase-initials-region~.

* [[http://www.vimgolf.com/challenges/53b473a3ac0ceb00022303bd][Do you demand a shrubbery?]]
<2017-01-31 Tue>

Normal edit.

* [[http://www.vimgolf.com/challenges/57a87f444f1a8e3c4000ff8c][Pretty multi-line bash]]
<2017-01-31 Tue>

~M-x align-regexp RET && RET~

* [[http://www.vimgolf.com/challenges/54698da795f6da00020d85ed][Condensed Cases]]
<2017-01-31 Tue>

# \nbsp stands for one space, see (info "(org) Special symbols") for
# more info
1. Set "\nbsp\nbsp\nbsp\nbsp{}case" as ~fill-prefix~ by moving point right after it and
   hitting ~C-.~ (or ~M-x set-fill-prefix~).
2. Join the line with previous one with ~M-^~ (or ~M-x
   delete-indentation~)
3. Replace " " with " ," by using query-replace on a region.

* [[http://www.vimgolf.com/challenges/5325695c6092800002072d06][Mess in revision history]]
<2017-01-31 Tue>

Use ~C-x SPC~ (~rectangle-mark-mode~) to mark the region and ~C-x r t~
(~string-rectangle~) to insert the leading spaces.

* [[http://www.vimgolf.com/challenges/5054baaafa0b390002000029][SFD-ROC: vimvimvim]]
<2017-01-31 Tue>

Replace "vim" with "vim\n" by typing ~M-x replace-string RET vim RET
vim C-q C-j RET~.

* [[http://www.vimgolf.com/challenges/56680033ac11043d6306aa07][Replace and keep the case]]
<2017-01-31 Tue>

Emacs by default does this, simply run ~M-%~ (~query-replace~) or just
~M-x replace-string~.

* [[http://www.vimgolf.com/challenges/580c21b5c177c54b0d067069][Start coding format]]
<2017-01-31 Tue>

Type it literally. CC Mode is powerful.

* [[http://www.vimgolf.com/challenges/51e023f92b2f6d0002000066][Hole-in-one]]
<2017-01-31 Tue>

Edit as usual.

* [[http://www.vimgolf.com/challenges/4d1e634e509d6e19d8000081][Shebangs for all]]
<2017-01-31 Tue>

Edit as usual.

* [[http://www.vimgolf.com/challenges/5447b459380e8b0002000db3][Gray area]]
<2017-01-31 Tue>

Edit as usual.

- Copy a region with ~M-w~ (~kill-ring-save~)
- Clear a region with ~C-x r c~ (~clear-rectangle~)
- Delete a region with ~C-w~ (~kill-region~)

* [[http://www.vimgolf.com/challenges/53369b712a09c1000223fb57][Two become one]]
<2017-01-31 Tue>

Edit as usual, nothing special.

* [[https://vimgolf.com/challenges/4ed3d247a745c1000100002a][remove dupes from array]]
<2017-01-31 Tue>

Start file

#+BEGIN_EXAMPLE
[11, 2, 3,5  , 1,1, 22, 4]
#+END_EXAMPLE

End file

#+BEGIN_EXAMPLE
[1, 2, 3, 4, 5, 11, 22]
#+END_EXAMPLE

** Solution

Mark the numbers in the region and run the following command.

#+BEGIN_SRC emacs-lisp
(defun sort-and-remove-dup-in-region (start end)
  (interactive "*r")
  (let* ((str (buffer-substring start end))
         (replace
          (mapconcat #'number-to-string
                     (sort (mapcar #'string-to-number
                                   (delete-dups (split-string str "[ ]*,[ ]*")))
                           #'<)
                     ", ")))
    (delete-region start end)
    (insert replace)))
#+END_SRC

* [[https://vimgolf.com/challenges/584dd156842bd00769000001][Double and switch]]
<2017-01-31 Tue>

Oh, I don't really know the answer and also don't have much interest
to find it out. I decide to give it up.

The following minor mode is for enlarge/shrink the region in binary
way, which might be helpful for answering this challenge.

#+BEGIN_SRC emacs-lisp
(defvar binary-region-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map [?+] #'binary-region+)
    (define-key map [?-] #'binary-region-)
    map))

(define-minor-mode binary-region-mode
  "用二分法扩大或缩小 the region."
  :lighter " Binary-Region"
  :keymap binary-region-mode-map)

(defun binary-region+ (start end)
  (interactive "r")
  (when (use-region-p)
    (set-mark start)
    (goto-char (+ (- end start) end))))

(defun binary-region- (start end)
  (interactive "r")
  (when (use-region-p)
    (set-mark start)
    (goto-char (+ (/ (- end start) 2) start))))
#+END_SRC

* [[https://vimgolf.com/challenges/4d1a71b5b8cb340932000109][Change the content of a string]]
<2017-01-31 Tue>

Edit as usual.

* [[https://vimgolf.com/challenges/54ddd1d261cec11d1b01707c][Mute the second method of this script]]
<2017-01-31 Tue>

1. Mark the method with ~C-M-h~ (~mark-defun~)
2. Comment the region with ~M-:~ (~comment-dwim~)

* [[https://vimgolf.com/challenges/50ae009b65b8db0002000047][Let's play some Ivmgolf]]
<2017-01-31 Tue>

1. Mark "Iv" across 4 lines in rectangle mode with ~C-x SPC~
   (~rectangle-mark-mode~)
2. ~C-x r t Vi RET~ (~string-rectangle~)

* [[https://vimgolf.com/challenges/57a021b0d938573add00bcd0][A grid of punctuation]]
<2017-01-31 Tue>

1. Record a keyboard macro for yanking "-=" and ~C-u 40 C-x e~
   (~kmacro-end-and-call-macro~) to yank 40 times
2. Make the second line by some manually edits
3. Do the similar thing in 1

* [[https://vimgolf.com/challenges/56462467f20fe74c93000001][lipsum lines]]
<2017-01-31 Tue>

1. Delete double-quotes
2. Wrap lines in ~"\1",~ with ~C-M-%~ (~query-replace-regexp~)
3. Cleanup

* [[http://www.vimgolf.com/challenges/4d1ccfde35b40650b80004ae][The Cake is a Lie]]
<2017-02-01 Wed>

Simply run ~M-c~ (~capitalize-word~) a few times.

1. Delete words with ~M-x replace-regexp RET [a-z ]* RET \n RET~
2. Record keyboard macro ~C-a C-SPC C-e " , M-^~ then mark the
   appropriate region and run ~M-x apply-macro-to-region-lines~
3. Cleanup

* [[http://www.vimgolf.com/challenges/4fc9d767d3a0d4000100000e][Append semicolon after expressions]]
<2017-02-01 Wed>

~C-M-% ^\(.+\)$ RET \1; RET~ (~query-replace-regexp~)

* [[http://www.vimgolf.com/challenges/4d1a5275a860b74472000110][Sort and add attributes]]
<2017-02-01 Wed>

1. Sort via ~M-x sort-lines~
2. Add attributes via
   ~M-x replace-string RET ) RET  , :country => "USA") RET~

* [[http://www.vimgolf.com/challenges/55d7692d134b34420f05ac0b][Add to end of each line... kinda]]
<2017-02-01 Wed>

Replace or query-replace as usual.

* [[http://www.vimgolf.com/challenges/4d1e29fda93ce03311000066][Ruby 1.9 hashes]]
<2017-02-01 Wed>

Use ~query-replace-regexp~ or ~rectangle-mark-mode~.

* [[http://www.vimgolf.com/challenges/4d1a6a8eb8cb34093200007a][Reconstruct the Sentence]]
<2017-02-01 Wed>

1. Sort lines with ~C-u -1 M-x sort-numeric-fields~
2. Join lines via ~M-x replace-regexp~

* [[http://www.vimgolf.com/challenges/54a8fb2ff4048c0002479f12][Happy TvvO]]
<2017-02-01 Wed>

Edit as usual.

* [[http://www.vimgolf.com/challenges/4fa0d2fa2037000001000057][Exchanging Quotes]]
<2017-02-01 Wed>

Replace

- ~'~ to ~"~
- ~\'~ to ~'~

with ~M-x plur-query-replace RET {',\'} RET {",'} RET~ (Notes that the
command is from plur package, which is written by me and available
from melpa)

* [[http://www.vimgolf.com/challenges/553b97364ba96c319d0296eb][readability]]
<2017-02-01 Wed>

Surround ~[-=*+/]~ with one space by using ~M-x replace-regexp~. Notes
that ~-~ is a special character in ~[]~, to include it, it should be
placed at the beginning or end of ~[]~.

* [[https://vimgolf.com/challenges/55771cc4750ef86573003b83][Line 'em up!]]
<2017-02-01 Wed>

~M-x align-regexp RET => RET~

* [[https://vimgolf.com/challenges/54e05c0e3da7a40ce4002226][ASCII box]]
<2017-02-03 Fri>

~M-x comment-box RET * RET~

* [[https://vimgolf.com/challenges/4d1cdb0635b40650b8000527][Make Fancy Header]]
<2017-02-03 Fri>

I don't know fancy method, simply edit as usual.

* [[https://vimgolf.com/challenges/53eb4ac3f690b50002f871b6][Lisp Condense]]
<2017-02-03 Fri>

Emacs understands Lisp. Type ~M-R~ (~paredit-raise-sexp~) or ~M-x raise-sexp~.

* [[https://vimgolf.com/challenges/56e69da07b3d84520a000001][Mirrored text]]
<2017-02-04 Sat>

#+BEGIN_SRC emacs-lisp
(defun chunyang-eval-on-region (beg end)
  (interactive "r")
  (let ((text (buffer-substring-no-properties beg end)))
    (eval (read--expression "Eval on region (local var: beg, end, text): "))))
#+END_SRC

~M-x chunyang-eval-on-region RET (kill-new (nreverse text)) RET~

* [[https://vimgolf.com/challenges/53e1d5a0f201bc0002226501][120 Degrees]]
<2017-02-04 Sat>

#+BEGIN_QUOTE
Rotate that triangle.
#+END_QUOTE

Start file

#+BEGIN_EXAMPLE
   4
  3 5
 2   6
1 9 8 7
#+END_EXAMPLE

End file

#+BEGIN_EXAMPLE
   4
  3 5
 2   6
1 9 8 7
#+END_EXAMPLE

** Solution

Select that triangle and execute the following command

#+BEGIN_SRC emacs-lisp
(defun rotate-that-triangle (beg end)
  (interactive "*r")
  (let* ((text (buffer-substring beg end))
         (list (split-string text))
         (sorted (loop for i in '(0 2 4 8 7 6 5 3 1)
                       collect (nth i list)))
         (rotated (append (seq-subseq sorted 3)
                          (seq-subseq sorted 0 3))))
    (goto-char beg)
    (loop for i in '(0 8 1 7 2 6 5 4 3)
          do
          (forward-to-word 1)
          (cl-destructuring-bind (b . e) (bounds-of-thing-at-point 'word)
            (delete-region b e)
            (insert (nth i rotated))))))
#+END_SRC

* [[https://vimgolf.com/challenges/4d1a4f2ba860b744720000bf][Flodder-challenge]]
<2017-02-04 Sat>

Use ~M-c~ (~capitalize-word~), ~M-u~ (~upcase-word~) and ~M-L~ (~downcase-dwim~).

* [[https://vimgolf.com/challenges/4d1c1a3cf655cd081000000d][A Simple One]]
<2017-02-04 Sat>

hmm, just delete the old and insert the new. Though,
~org-increase-number-at-point~ works (prefix with ~C-u 25~ and
 ~C-u 49~).

* [[https://vimgolf.com/challenges/54f6e85d8dca0315e1010de1][Logging with key]]
<2017-02-04 Sat>

Edit as usual.

* [[https://vimgolf.com/challenges/56a260eedb173f2f5d00f6f8][JS notation to Immutable.js notation]]
<2017-02-04 Sat>

Use keyboard macro and rectangle region mode.

* [[https://vimgolf.com/challenges/4d1b1b97c58eaa2a8a0002fc][Python Hello World! Reformatting]]
<2017-02-04 Sat>

Edit as usual.

* [[https://vimgolf.com/challenges/521c805d860021000200007d][VimGolfNight]]
<2017-02-04 Sat>

Edit as usual.

* [[https://vimgolf.com/challenges/50519ca330c82d0002000035][The name of the game]]
<2017-02-04 Sat>

Edit as usual.

* [[https://vimgolf.com/challenges/50d0d80eaa503f000200001b][Swap assigned value]]
<2017-02-05 Sun>

Use ~swap-regions~.

* [[https://vimgolf.com/challenges/4d1db1b8de2f897c2a00014a][Reverse Simple Deletion]]
<2017-02-05 Sun>

~C-M-% . RET \& C-q C-j RET~ (~query-replace-regexp~)

* [[https://vimgolf.com/challenges/5107179a44d65e0002000048][Minimalist Limerick]]
<2017-02-05 Sun>

Edit as usual.

* [[https://vimgolf.com/challenges/53ab5ade4367c700025ce66a][Shuffle puzzle]]
<2017-02-05 Sun>

Edit as usual.

* [[https://vimgolf.com/challenges/4d3c51f1aabf526ed6000030][HTML to Haml]]
<2017-02-06 Mon>

Edit as usual.

* [[https://vimgolf.com/challenges/55358965015b7c2d46000001][Shuffled numbers]]
<2017-02-06 Mon>

Select the region and execute the following command.

#+BEGIN_SRC emacs-lisp
(defun my-sort-lines (reverse beg end)
  (interactive "P\nr")
  (save-excursion
    (save-restriction
      (narrow-to-region beg end)
      (goto-char (point-min))
      (let ;; To make `forward-word' and etc. to ignore fields.
          ((inhibit-field-text-motion t))
        (sort-subr reverse 'forward-line 'end-of-line nil 'forward-word
                   (lambda (x y)
                     (let ((list '(zero
                                   one two three four five
                                   six seven eight nine ten
                                   eleven twelve thirteen fourteen fifteen
                                   sixteen seventeen eighteen nineteen twenty))
                           (s1 (buffer-substring (car x) (cdr x)))
                           (s2 (buffer-substring (car y) (cdr y))))
                       (< (seq-position list (intern s1))
                          (seq-position list (intern s2))))))))))
#+END_SRC

* [[https://vimgolf.com/challenges/4d2c9d06eda6262e4e00007a][Assignment Alignment]]
<2017-02-06 Mon>

~M-x align-regexp RET = RET~

* [[https://vimgolf.com/challenges/4f99b09353e306000100003f][The meaning]]
<2017-02-07 Tue>

Go to the line end via ~C-e~ (~move-end-of-line~) and swap the chars
with ~C-t~ (~transpose-chars~).

* [[https://vimgolf.com/challenges/50bda7a73645b3000200004b][lamb had a little Mary]]
<2017-02-07 Tue>

Use ~M-x plur-replace~ or ~M-x query-replace-regexp~.

* [[https://vimgolf.com/challenges/50ee7504c0e3aa0002000040][Prefixes and suffixes]]
<2017-02-07 Tue>

Use keyboard macro.

* [[https://vimgolf.com/challenges/55e814a35f5608403d000001][Vim's not included features]]
<2017-02-07 Tue>

#+BEGIN_SRC emacs-lisp
(while (re-search-forward "-[_[:word:]]+" nil t)
    (message "%s" (match-string 0)))
#+END_SRC

Notes that the order is not the same as the end file.

* [[https://vimgolf.com/challenges/56e3697dd64dfc4d1800a774][Free hyphen!]]
<2017-02-07 Tue>

Do it manually or record a keyboard macro.

* [[https://vimgolf.com/challenges/525ee6a5de92470002000039][Split the words]]
<2017-02-07 Tue>

Do it manually or simply ignore this challenge.

* [[https://vimgolf.com/challenges/4d4ab047795d626036000034][imports alignment (python)]]
<2017-02-07 Tue>

Do it manually.

* [[https://vimgolf.com/challenges/56d30b70a365ed316105641b][Sorting a glossary]]
<2017-02-07 Tue>

Kill and Yank.

* [[https://vimgolf.com/challenges/51103ad8041832000200003f][vim = 22 / 7]]
<2017-02-07 Tue>

Use keyboard macro.

* [[https://vimgolf.com/challenges/51d6ddf4b0c5d6000200002e][Pairs of numbers]]
<2017-02-07 Tue>

Execute the following command:

#+BEGIN_SRC emacs-lisp
(defun foo ()
  (interactive)
  (let (numbers)
    ;; Collect numbers
    (while (re-search-forward "-?[.0-9]+" nil t)
      (push (match-string 0) numbers))
    (setq numbers (nreverse numbers))

    ;; Compute and insert the result
    (goto-char (point-max))
    (seq-let (group1 group2) (seq-partition numbers (/ (length numbers) 2))
      (seq-mapn
       (lambda (x y)
         (insert (format "[%s, %s]\n" x y)))
       group1 group2))))
#+END_SRC

* [[https://vimgolf.com/challenges/4d1aaf2fb11838287d000036][Reverse characters in a line]]
<2017-02-07 Tue>

~M-: (insert (nreverse "text"))~ (~eval-expression~)

* [[http://www.vimgolf.com/challenges/53fdb108658ede0002599a8f][Suffix sort]]
<2017-02-08 Wed>

Select the region and run the command:

#+BEGIN_SRC emacs-lisp
(defun suffix-sort (beg end)
  "Sort from the end of the line, as if the letters in each line were reversed."
  (interactive "*r")
  (save-excursion
    (save-restriction
      (narrow-to-region beg end)
      (goto-char (point-min))
      (sort-subr nil #'forward-line #'end-of-line nil nil
                 (lambda (x y)
                   (let ((s1 (buffer-substring (car x) (cdr x)))
                         (s2 (buffer-substring (car y) (cdr y))))
                     (string< (nreverse s1)
                              (nreverse s2))))))))
#+END_SRC

* [[http://www.vimgolf.com/challenges/50502d985cfbf50002000022][NATO phonetic alphabet]]
<2017-02-08 Wed>

1. Use ~M-%~ (~query-replace~) to split text into lines
2. Use ~C-x r M-w~ (~copy-rectangle-as-kill~) and ~C-x r y~
   (~yank-rectangle~) to add the prefix

* [[http://www.vimgolf.com/challenges/508fe9f57acca60002000037][Stairs Indenting]]
<2017-02-08 Wed>

~C-M-% [0-9]+ RET \,(format "%s%s" (make-string (string-to-number \&) ? ) \&) RET~ (~query-replace-regexp~)

Tips:
- Use ~\,~ to follow a sexp
- Use ~\&~ to denote the whole match

* [[http://www.vimgolf.com/challenges/4d1a790fb8cb3409320001a8][Reformat most common surnames]]
<2017-02-08 Wed>

1. Remove unneed parts with ~C-M-%~ (~query-replace-regexp~)
2. Fix cases by select the region and ~M-x capitalize-dwim~
3. Add number prefix with ~C-u C-x r N %d. RET~ (~rectangle-number-lines~)

* [[http://www.vimgolf.com/challenges/50af864132b7ed0002000075][A simple change]]
<2017-02-08 Wed>

Edit as usual.

* [[http://www.vimgolf.com/challenges/4d1a6bafb8cb34093200008e][Wrap the text of an email message to 79 characters]]
<2017-02-08 Wed>

1. Change ~fill-column~ to 79 with ~C-x f~ (or ~M-x set-fill-column~)
2. Change ~fill-prefix~ to "> " with ~C-x .~ (or ~M-x set-fill-prefix~)
3. Fill with ~M-q~ (~fill-paragraph~) (need to go through step 2)

* [[http://www.vimgolf.com/challenges/4f026d9b50582b000100002e][Replacing some words]]
<2017-02-08 Wed>

Pass (not very meaningful).

* [[http://www.vimgolf.com/challenges/4dcd7b572c8e510001000005][Interweave two blocks of text]]
<2017-02-08 Wed>

1. Make "one two ..." the same width
2. Copy and yank the numbers with ~C-w~ (~kill-region~) and ~C-x r y~
   (~yank-rectangle~)

* [[http://www.vimgolf.com/challenges/4d1ac1800a045132c0000011][Reformat a C golf submission]]
<2017-02-08 Wed>

Edit as usual.

* [[http://www.vimgolf.com/challenges/4d1a6ed2b8cb3409320000c9][Add fold markers to a .c file]]
<2017-02-08 Wed>

Edit as usual or simply pass (makes no sense for Emacs).

* [[http://www.vimgolf.com/challenges/4d1cc35a35b40650b800043a][Increment, increment, increment....]]
<2017-02-08 Wed>

Recoard the macro with ~M-1 F3 F3 RET F4~ and execute the macro repeatly.

- ~M-1 F3~ to start recoarding and set keyboard macro counter to 1 (defaults to 0)
- the second ~F3~ to insert the counter

Notes that keyboard macro counter is incremented each time its value
is inserted into the buffer. For more info, see [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Keyboard-Macro-Counter.html][(emacs) Keyboard Macro Counter]].

* [[http://www.vimgolf.com/challenges/4d1b76d9c58eaa2a8a000866][Context insensitive completion 0]]
<2017-02-08 Wed>

Pass (I don't understand the question and have no interest to find out).

* [[http://www.vimgolf.com/challenges/4d1b3d57c58eaa2a8a000510][Sorting paragraphs]]
<2017-02-08 Wed>

~M-x sort-paragraphs~

* [[https://vimgolf.com/challenges/53d1f9344ab5290002ab30e0][Subtraction]]
<2017-02-08 Wed>

Run ~C-M-%~ (~query-replace-regexp~) with the following arguments.

#+BEGIN_SRC emacs-lisp
^\(x+\) - \(.+\) =$  =>  \1 - \2 = \,(make-string (- (length \1) (length \2)) ?x)
#+END_SRC

/Wow, being able to run arbitrary Lisp is really awesome./

* [[https://vimgolf.com/challenges/50be61aea748a30002000047][abcd > a b c d]]
<2017-02-08 Wed>

Replace one space with one tab via ~M-%~ (~query-replace~).

* [[https://vimgolf.com/challenges/4ea9bc988b36f70001000008][Sort entries based on date]]
<2017-02-08 Wed>

Select the region and run the command:

#+BEGIN_SRC emacs-lisp
;; Adapt from `sort-paragraphs'
(defun sort-paragraphs-based-on-date (reverse beg end)
  (interactive "P\nr")
  (save-excursion
    (save-restriction
      (narrow-to-region beg end)
      (goto-char (point-min))
      (sort-subr reverse
                 (lambda ()
                   (while (and (not (eobp)) (looking-at paragraph-separate))
                     (forward-line 1)))
                 #'forward-paragraph
                 nil
                 (lambda ()
                   (re-search-forward
                    (rx (repeat 2 (in digit)) "."
                        (repeat 2 (in digit)) "."
                        (repeat 4 (in digit)))))
                 (lambda (x y)
                   (let ((s1 (buffer-substring (car x) (cdr x)))
                         (s2 (buffer-substring (car y) (cdr y))))
                     (< (string-to-number (apply #'concat (nreverse (split-string s1 "\\."))))
                        (string-to-number (apply #'concat (nreverse (split-string s2 "\\.")))))))))))
#+END_SRC

/~sort-subr~ is simply amazing/

* [[https://vimgolf.com/challenges/513b1dcd2d1ae10002000010][Sort the VimGolf challenges by popularity]]
<2017-02-08 Wed>

1. Remove unneeded lines with ~M-x delete-non-matching-lines~
2. Sort lines with ~C-u -2 M-x sort-numeric-fields~
3. Reverse lines with ~M-x reverse-region~

* [[https://vimgolf.com/challenges/52552abfb089a00002000007][Create Leading Zeros]]
<2017-02-08 Wed>

Run ~C-M-%~ (~query-replace-regexp~) with the following arguments.

#+BEGIN_EXAMPLE
^[0-9]+  =>  \,(format "%04d" (string-to-number \&))
#+END_EXAMPLE

* [[https://vimgolf.com/challenges/544bcdd93cafc700021ee30e][learn vim in short time]]
<2017-02-08 Wed>

Edit as usual.

* [[https://vimgolf.com/challenges/55389fb1d6367c11201571d1][remove all lines in first part]]
<2017-02-08 Wed>

Make the region and type ~M-x delete-duplicate-lines~.

* [[https://vimgolf.com/challenges/56e4fe988cf590220106e9bb][Fun With The Diagonal]]
<2017-02-08 Wed>

Record keyboard macro ~M-c C-n~ and run it for several times.

* [[https://vimgolf.com/challenges/4d1e037dde2f897c2a000417][Reverse and count]]
<2017-02-08 Wed>

1. Reverse with ~M-x reverse-region~
2. Count with ~C-u C-x r N RET RET %d. RET~

* [[https://vimgolf.com/challenges/4d2478e20947c63e2600009c][Insert a Markdown link]]
<2017-02-08 Wed>

Do it manually or use feature provided by markdowm-mode (check the
Menu Bar).

* [[https://vimgolf.com/challenges/4d26f42298e8d72471000025][Generate English Alphabets]]
<2017-02-08 Wed>

#+BEGIN_SRC emacs-lisp
(loop for i from ?a to ?z
      do (insert i ?\n))
#+END_SRC

* [[https://vimgolf.com/challenges/4d34af20e747f561b3000081][Rotating Philosophers Problem]]
<2017-02-09 Thu>

Use Keyboard Macro.

* [[https://vimgolf.com/challenges/4d1b9703c8bb5704eb000081][Hatsuyume]]
<2017-02-09 Thu>

Select the region and type ~C-u M-| nl -s ' ' -w 1 RET~ (~shell-command-on-region~).

Notes that for nl(1) from GNU Coreutils:
- ~-s STRING~ / ~--number-separator=STRING~ :: Separator
- ~-w NUMBER~ :: ~--number-width=NUMBER~ :: Width

* [[https://vimgolf.com/challenges/55054f0ac64edd79b00265ac][Interleave lines]]
<2017-02-09 Thu>

Kill-and-yank as usual.

* [[https://vimgolf.com/challenges/54a480bb5db1600002939b54][increment by column in XML]]
<2017-02-09 Thu>

Run ~C-M-%~ (~query-replace-regexp~) with the following arguments

#+BEGIN_EXAMPLE
@@@@@  =>  \,(number-to-string (+ 10000 \#))
#+END_EXAMPLE

Notes that
- ~\,~ starts a Lisp expression
- ~\#~ means the number of replacements done so far (starting with 0)

/query-replace-regexp is awesome/

* [[https://vimgolf.com/challenges/53cee5e1c5f4b4000208b285][Change name of a variable]]
<2017-02-09 Thu>

Edit as usual.

* [[https://vimgolf.com/challenges/546a627195f6da000265742d][Pretty format for variable declarations]]
<2017-02-09 Thu>

~M-x align-regexp RET = RET~

* [[https://vimgolf.com/challenges/50b5266f448d770002000106][Readable Rubyhash]]
<2017-02-09 Thu>

Use ~C-M-%~ (~query-replace-regexp~).

* [[https://vimgolf.com/challenges/50d42c56dffb94000200000c][Enumerate words]]
<2017-02-09 Thu>

1. Split text into lines with ~C-M-% [[:punct:] ] RET C-q C-j RET~ (~query-replace-regexp~)
2. Delete empty lines with ~M-x delete-matching-lines RET ^$~
3. Capitalize lines by selecting the region and type ~M-x capitalize-dwim~
4. Sort lines with ~M-x sort-lines~

* [[http://www.vimgolf.com/challenges/4d28637c4bcd032f1c00003d][Reformat long lines]]
<2017-02-10 Fri>

Edit normally.

* [[http://www.vimgolf.com/challenges/4d1bfa8fb2c3e06468000127][Table Reshuffle]]
<2017-02-10 Fri>

Record keyboard macro. Note that
1. Use ~M-t~ (~transpose-words~)
2. Use ~C-M-w~ (~append-next-kill~)

* [[http://www.vimgolf.com/challenges/51b4e3b920faf70002000001][Number an outline]]
<2017-02-10 Fri>

#+BEGIN_SRC emacs-lisp
(defvar english-number-alist '((One   . 1)
                               (Two   . 2)
                               (Three . 3)
                               (Four  . 4)
                               (Five  . 5)
                               (Six   . 6)))
#+END_SRC

and run ~C-M-%~ (~query-replace-regexp~) with the following arguments

#+BEGIN_EXAMPLE
[0-9]\. \(\w+\)$  =>  \,(format "%d. %s" (alist-get (intern \1) english-number-alist) \1)
#+END_EXAMPLE

* [[http://www.vimgolf.com/challenges/4d1a7a05b8cb3409320001b4][Get rid of html tags]]
<2017-02-10 Fri>

Delete tags with ~C-M-% <.+?> RET RET~ (~query-replace-regexp~)

* [[http://www.vimgolf.com/challenges/55e704665f560803fa000001][Assign numbers to fields]]
<2017-02-10 Fri>

~C-M-% \w+ RET \#:\& RET~ (~query-replace-regexp~)

* TODO [[http://www.vimgolf.com/challenges/556d7209f6d1a10ee6000001][swap or reverse]]
<2017-02-10 Fri>

* [[http://www.vimgolf.com/challenges/50f3c2d55c891f0002000002][Word frequency alignment]]
<2017-02-10 Fri>

~M-x align-regexp RET [0-9] RET~

* [[http://www.vimgolf.com/challenges/53f388dfb2a65900028494ae][NBCU Weekly Challenge - #0]]
<2017-02-10 Fri>

Edit as usual.

* [[http://www.vimgolf.com/challenges/4d1e93e825ba287b2a0000ed][The holy-grail may help]]
<2017-02-10 Fri>

Edit as usual.

* [[http://www.vimgolf.com/challenges/54cb9296b2df9e000307809a][Winning streak]]
<2017-02-10 Fri>

Use ~C-x r N~ (~rectangle-number-lines~) and cut-and-paste the rectangle region.

* [[https://vimgolf.com/challenges/50e32889d5e627000200000d][Change your calendar]]
<2017-02-11 Sat>

Delete the old and insert the new one via ~M-x calendar~.

* [[https://vimgolf.com/challenges/4e5ec5851836e0000100003e][Alphabetize the directory]]
<2017-02-11 Sat>

Paste text into an Org buffer and sort headings with ~C-c ^~ (~org-sort~).

* [[https://vimgolf.com/challenges/5486c522908f4600023c53fa][Test everything!]]
<2017-02-11 Sat>

Use keyboard macro as usual.

* [[https://vimgolf.com/challenges/51cf1fae5e439e0002000001][Top X]]
<2017-02-11 Sat>

1. Split into lines by replacing space into newline via ~M-%~ (~query-replace~)
2. Remove duplicates via ~M-x delete-duplicate-lines~
3. Join lines by replaing newline into space via ~M-%~ (~query-replace~)

* [[https://vimgolf.com/challenges/5598ef76c0132f45c9005238][Entries sort]]
<2017-02-11 Sat>

1. Cut parts accros lines
2. Sort lines
3. Paste them back

* [[https://vimgolf.com/challenges/512eda055d6ed80002000025][Parsing with CSV: Unify lines and result.]]
<2017-02-11 Sat>

Edit manually.

* [[https://vimgolf.com/challenges/51cd1be19f3290000200000e][Assign list]]
<2017-02-11 Sat>

Use ~M-%~ (~query-replace~) and keyboard macro.

* [[https://vimgolf.com/challenges/4d1c6d0535b40650b800017e][Compile C]]
<2017-02-11 Sat>

~C-u M-! cc foo.c && ./a.out~ (~shell-command~)

* [[https://vimgolf.com/challenges/5078889ceedfc90002000047][Python to Ruby]]
<2017-02-11 Sat>

Edit as usual.

* [[https://vimgolf.com/challenges/4d1a87fcb8cb340932000290][Deleting folded text]]
<2017-02-11 Sat>

Select the region via isearch and delete text in the region, since it
is not easy to build regexp for it.

* [[https://vimgolf.com/challenges/4fe62f8a8b2f800001000043][Cleanining up 80 column concatenated text]]
<2017-02-12 Sun>

Cut-and-paste. Notes that use ~C-M-w~ (~append-next-kill~).

* [[https://vimgolf.com/challenges/4d1be79bb2c3e064680000c6][Fix the Haiku]]
<2017-02-12 Sun>

Use ~M-c~ (~capitalize-word~) and ~C-x r t~ (~string-rectangle~).

* [[https://vimgolf.com/challenges/56fcc3204a7725120c00c91c][SQL to YAML]]
<2017-02-12 Sun>

Pass (or use keyboard macro and maybe plus some manual edits).

* [[https://vimgolf.com/challenges/4d1d0d5e35b40650b8000711][82 bottles of beer on the wall]]
<2017-02-12 Sun>

Duplicates the text 82 times and ~C-M-%~ (~query-replace-regexp~).

* [[https://vimgolf.com/challenges/511991607729fb0002000003][Refactor arguments into object argument]]
<2017-02-12 Sun>

Pass (or edit manually).

* [[https://vimgolf.com/challenges/4d1c27940e3d7832db000010][Prime Numbers]]
<2017-02-12 Sun>

#+BEGIN_SRC emacs-lisp
(defun prime-numbers (until)
  (assert (> until 1))
  (loop for n from 2 to until
        if (loop for i from 2 to (1- n)
                 if (= 0 (% n i))
                 return nil
                 finally return t)
        collect n))

(insert (mapconcat #'number-to-string (prime-numbers 542) "\n"))
#+END_SRC

* [[https://vimgolf.com/challenges/50c2c246b0544c000200003f][Block Fun 1]]
<2017-02-12 Sun>

Recoard keyboard macro which uses ~C-x r M-w~
(~copy-rectangle-as-kill~) and ~C-x r y~ (~yank-rectangle~).

* [[https://vimgolf.com/challenges/54c392acbd7cbe0003329b7c][Separating firstname & lastname]]
<2017-02-12 Sun>

Type ~C-u M-x align-regexp~ with the following arguments:

#+BEGIN_EXAMPLE
 \(\) -> RegExp
1     -> Group 1
6     -> 6 white spaces
y     -> Repeat (Don't not matter in this case)
#+END_EXAMPLE

* [[https://vimgolf.com/challenges/55faae943e9b67549b000001][Sudoku table]]
<2017-02-12 Sun>

Use Rectangle Region Mode heavily.

* [[https://vimgolf.com/challenges/4d665abd7d73e02a55000009][Java Array2List]]
<2017-02-12 Sun>

Run ~C-M-%~ (~query-replace-regexp~) with the following arguments

#+BEGIN_EXAMPLE
\([0-9.]+\),? ?  =>  c.add(\1);
#+END_EXAMPLE

* [[https://vimgolf.com/challenges/543e53c037ba3a00022b3ec7][Winding path]]
<2017-02-14 Tue>

Edit manually (use keyboard macro if convenient)

* [[https://vimgolf.com/challenges/5035e5b3838d9e000200006d][Dehamlizing]]
<2017-02-14 Tue>

Edit manually or use haml directly.

* TODO [[https://vimgolf.com/challenges/4fe9ab8b5089660001000002][Shuffle and Sort]]
<2017-02-14 Tue>

* [[https://vimgolf.com/challenges/54fb143d91984a0e75007579][Fill visual area]]
<2017-02-14 Tue>

Pass.

* [[https://vimgolf.com/challenges/5491377167afde00024ba4cf][Refactoring useless Method away]]
<2017-02-14 Tue>

Use keyboard macro.

* [[https://vimgolf.com/challenges/4d1c5e6035b40650b8000111][Another Mixed-Up Haiku]]
<2017-02-14 Tue>

Use keyboard macro.

* [[https://vimgolf.com/challenges/4d6f45b938c0aa691b000003][Recursively Palindrome]]
<2017-02-14 Tue>

Insert a ~a~ in a new line then run the following command for 5 times.

#+BEGIN_SRC emacs-lisp
(defun palindrome ()
  "Palindrome current line."
  (interactive)
  (let* ((beg (line-beginning-position))
         (end (line-end-position))
         (line (buffer-substring beg end))
         (next (1+ (nth (/ (1- (length line)) 2)
                        (string-to-list line)))))
    (delete-region beg end)
    (insert (format "%s%c%s" line next line))))
#+END_SRC

* [[https://vimgolf.com/challenges/4fdb12a383de630001000005][Aligning function arguments to match a specific coding style]]
<2017-02-14 Tue>

Run ~C-u M-x align-regexp~ with ~[^ ]\( \)[^ ]~.

* [[https://vimgolf.com/challenges/5508d1ded05c5e2a710d7e93][Rail fence transposition cipher]]
<2017-02-14 Tue>

Pass.

* [[https://vimgolf.com/challenges/4dab05bff1161c5a78000011][Sort the cardinal numbers]]
<2017-02-14 Tue>

Edit manually.
